apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgBIjbF4WW3YXq2MOVrgk1G4/75e1lVhYOoQREP5npab/aWE9W7tggaRV3B1jWZNaxkUloi6zEbGCbvdxCVD1NdLUN7F4dSFZA7lUCEUH2IopAe+29lL7NPWET85qZXCoaY2VvYPuh3WJdCfO80vFO5Ky6jmd8wOCuKqnL28xkCXlgbYY1H5BLYuIyEfEFX7i/CeBynaGLiiWgcSFKKd0B917akWyYlYtO+J2T48tz6Yo2hO0RheiUp4X3xJYx+P7ToNuLJoyRJzgWZ0DKkIsFe9rMlxEW9wwmk41pKuGJzEFdTr1aCSXhOc6WlRp4kM9GJW5dPYhNIuRqXqtfmOrBS1EZgzyoccjYqDOXRfXwe+ClHSnNKwR2ztVtIw9RVDjw/d8iwLYtc68fQLeF58h0XpCRn+Ma6T8Ho802AwKMds9OXd3V08xCrjeUy2JgYDGLV+4WBH8Nk7cTxKmfFP7sf9wVj1bqxSwTR9z8YmbsezyLAliwGiGdSny7671XcszeuaIQQ/fzIwZdeh4Q+A2fqONPTPdA4JPBsxmHA2eOgXHTHC9RNSlt0g0kaNJGSA8xkfQf1KGgneFE4EP/RoVP4/T6V8Lnsy0raAmpJ05zJ77yDaJYqnr8MWImSJ73En2WEfSzZfxfc0K92FYK9TuE3q+2d0LO9FoXLGtOmbYqBpbe7oaMBXdIk80LBZHbsHjmDtlz+ZoMtt9ZHoM3GugrnGs/vKKRb2ifAQqd1O+6ptIDNt8PEMbSDWevRJyJIQvgWMjfL/pZOZrL3Qa4s4rlVnCjJI9WaZGGzea/oQ6Xtdfnp3MORjIMpIOx8UZbr11n/Lv/U8oFuhdFUGjSRTcTFkllX+Bv+tfe7G1xb8rQimdf+rpQ13DA+klJ3I6srLgYeAZRcdghv0Q0dT/93Un/rc0+lP7BQOsdTo2RRpIUIKoOksnzQF5dk=
  template:
    data: null
    metadata:
      name: htpasswd-secret
      namespace: openshift-config
    type: Opaque

